### ISSUE TITLE
Random sort

### ISSUE THREAD

**Issue by trigras** [solr-express/solr-express#110]
Did not find the way to perform random sort: https://lucene.apache.org/solr/5_2_1/solr-core/org/apache/solr/schema/RandomSortField.html

Is this feature supported?

**Comment by diegobrum** [comment]
Nop.... but.. Why not?

**Comment by diegobrum** [comment]
Just a trick

If it is necessary to now, you can do this using one of below ways:
1 - Create a field called "random" in your document and use "SortParameter" parameter
2 - Set CheckAnyParameter (in DocumentCollection's Configuration) to false and use "AnyParameter" using value "sort=random asc|desc"

**Comment by diegobrum** [comment]
And a Bug in SOLR4 was fixed.
When 2 sort paramaters was added in distinct commands, a wrong command was created:

`
query.Sort(q=>q.Id, true);
query.Sort(q=>q.Descr, true);
`

> In this case, SolrExpress generated **",sort=Id ascDescr desc"** rather than **'sort=Id asc, Descr desc'**
