### ISSUE TITLE
Use Schema API

### ISSUE THREAD

**Issue by diegobrum** [solr-express/solr-express#112]
To avoid use of a lot of properties in SolrFieldAttribute, verify field definition with Schema API

i.e: [GET] http://localhost:8983/solr/demo/schema/fields/id

ref: http://yonik.com/solr-5-1/ (Schema API can remove and replace fields)

**Comment by stanuku** [comment]
@diegobrum: I ran the API for my Solr core and got this response. It seems to be deprecated.

```{
  "responseHeader":{
    "status":0,
    "QTime":597},
  "field":{
    "name":"ProjectId",
    "type":"int",
    "multiValued":false,
    "indexed":true,
    "required":true,
    "stored":true,
    "uniqueKey":true},
  "warn":"This API is deprecated"} <-- NOTE THIS

```

**Comment by diegobrum** [comment]
@stanuku 
Please, give me some informations:

- SOLR Express version
- Using Solr4 or Solr5 package?
- SOLR version
- Full query sent to SOLR (than created informed response)

**Comment by stanuku** [comment]
@diegobrum I used the Solr Admin UI. We are running Solr 5.5.3.

I tried the Schema API for one of my fields (ProjectId):

API URL: ```http://my-server:8983/solr/mycore/schema/fields/ProjectId```

Response:
```
{
  "responseHeader":{
    "status":0,
    "QTime":11},
  "field":{
    "name":"ProjectId",
    "type":"int",
    "multiValued":false,
    "indexed":true,
    "required":true,
    "stored":true,
    "uniqueKey":true},
  "warn":"This API is deprecated" <---
}
```

**Comment by diegobrum** [comment]
@stanuku Understood

I need research another approach to do this.
