### ISSUE TITLE
SpatialFilter not giving results as expected

### ISSUE THREAD

**Issue by Mountblanc** [solr-express/solr-express#148]
Hi,

When i use the following:
**query.SpatialFilter(q => q.pc_coords, SolrSpatialFunctionType.Geofilt, new SolrExpress.Core.GeoCoordinate(52.9127M, 4.7818799M), 1M);**

I get results but not the results that are closest to given location.
If i do the same in the Solr panel:
&fq={!geofilt sfield=pc_coords}&pt=52.9127,4.7818799&d=1

I get the results i would expect.
Even if the record coordinates match exactly the given coordinates then it is only returned if i set the max. distance at 2 or higher.

I use Solr5

**Comment by diegobrum** [comment]
Hi @Mountblanc 

Some questions:
* What is exact Solr 5 version?
* What is Solr.Express version?
* Do you have some default parameters configured in Query Handler (solr-config.xml)?
* Can you show your results when you use Solr panel?

Tks ^^

**Comment by diegobrum** [comment]
Hi @Mountblanc 
I found the bug and it will be fixed in next version

**Comment by Mountblanc** [comment]
Thanks! that is good news! I was just about to gather all the data but there is no need anymore....
Sure glad you fixed it!

**Comment by diegobrum** [comment]
Hi @Mountblanc 

Bug fixed... pay attention in change logs :)

**Comment by Mountblanc** [comment]
Thanks! Changes logs could not help me enough to get the things on the road again.
Luckily the  unit test sources gave me the complete picture on the changes needed.

The results with SpatialFilter are now working. (.net core Solr 5, Solr-express 4.0.0)
