### ISSUE TITLE
Query by multiple parameters

### ISSUE THREAD

**Issue by lgtelles** [solr-express/solr-express#162]
It would be very useful to have some way to pass a field and multiple values so the framework could generate something like 'id:[1 OR 2 OR 3']

**Comment by hheexx** [comment]
What is current way of doing this?

Maybe we can add function that translates array to param list?

**Comment by diegobrum** [comment]
@hheexx 

Current way is:

```
var ids = new []{1, 2, 3};
var query= string.Concat("(", string.Join(" OR ", ids), ")");

documentCollectionCompany
 .Select()
 .Filter(q => q.Id, query);
```

**Comment by hheexx** [comment]
For some reason that does not work when I pass in JArray.
I end up with new rows in string:
` "ptId:([\r\n  1,\r\n  2,\r\n  3,\r\n  4,\r\n  5\r\n])"`

I had to write it like this:

```
        private string ParamOrJoin( IEnumerable array ) {
            var l = new List<string>();
            foreach ( var el in array ) {
                l.Add( el.ToString() );
            }
            return string.Concat( "(", string.Join( " OR ", l ), ")" );
        }
```

**Comment by diegobrum** [comment]
Hi @lgtelles and @hheexx , please take a look in v5
