### ISSUE TITLE
Fields parameter (Solr5) should be parsed to "fl:" instead of "fields"

### ISSUE THREAD

**Issue by stanuku** [solr-express/solr-express#174]
**@diegobrum: I appreciate your awesome work. Thank you!** 

Here is my issue:
When performing a search, if we want Solr to return only certain fields in the docs:[] json, then the "fl" parameter should be populated in the query params. i.e. I don't want to fetch all the fields for the matching docs. For example: I need only the Unique Keys returned. Then using the keys I could access a data repository (for example, Database) to get more details about that document. By doing this the payload on the wire is significantly reduced. And, of course I don't store all the info in Solr and I do have to hit a repository after the search comes back.

Example: I have a Document with ProjectId as the unique key.
```
public class ProjectDocument : IDocument
{
        [SolrField("ProjectId", Indexed = true, Stored = true)]
        public int ProjectId { get; set; } // Unique Key
        [SolrField("ProjectNum ", Indexed = true, Stored = true)]
        public string ProjectNum { get; set; }
        [SolrField("ProjectTitle", Indexed = true, Stored = true)]
        public string ProjectTitle { get; set; }
}
```
And I search for matching documents based on Project Number field as:
```
var single = new Single<ProjectDocument>(p => p.ProjectNum, $"{projectNum}");
ISolrSearch<ProjectDocument> select = _projects
    .Select()
    .Fields(pd => pd.ProjectId) //Note: I only want the Unique Key i.e. ProjectId to be fetched from Solr
    .Query(single)
    .Page(50, 10);

select
    .Execute()
    .Document(out documents)
    .Information(out information) ;
```

The "documents" returned has all the Fields populated. i.e. the Fields(pd => pd.ProjecId) is not working as I expected. I expect only ProjectId to be populated in the documents list.

**I have a fix in my local fork of the repo, the code is below, should I send a pull request?**:
```
using Newtonsoft.Json.Linq;
using SolrExpress.Core;
using SolrExpress.Core.Extension.Internal;
using SolrExpress.Core.Search;
using SolrExpress.Core.Search.Parameter;

namespace SolrExpress.Solr5.Search.Parameter
{
    public sealed class FieldsParameter<TDocument> : BaseFieldsParameter<TDocument>, ISearchParameter<JObject>
        where TDocument : IDocument
    {
        /// <summary>
        /// Execute the creation of the parameter "sort"
        /// </summary>
        /// <param name="jObject">JSON object with parameters to request to SOLR</param>
        public void Execute(JObject jObject)
        {
            var jObj = (JObject)jObject["params"] ?? new JObject();
            foreach (var expression in this.Expressions)
            {
                var value = expression.GetFieldNameFromExpression();

                if (jObj["fl"] == null)
                {
                    var jArray = new JArray { value };
                    jObj.Add(new JProperty("fl", jArray));
                }
                else
                {
                    ((JArray)jObj["fl"]).Add(value);
                }
            }
            jObject["params"] = jObj;

            //var jArray = (JArray)jObject["fields"] ?? new JArray();
            //foreach (var expression in this.Expressions)
            //{
            //    var value = expression.GetFieldNameFromExpression();
            //    jArray.Add(value);
            //}
            //jObject["fields"] = jArray;
        }
    }
}
```

**Comment by diegobrum** [comment]
Hi @stanuku !

First of all, thanks a lot! :D

In Solr 5 I used [**JSON Request API feature**](https://cwiki.apache.org/confluence/display/solr/JSON+Request+API), and some params had names changed from Solr 4 Default Request Handler (i.e. *fl* to *fields*).

But, I add some params in query using a class called **SystemParameter** (to add some params and make sure that query will work)... this works well in Solr 4, but not in Solr 5.

I created a issue to explain the problem (#175) and I will fix this ASAP.

Thanks for your feadback

**Comment by diegobrum** [comment]
@stanuku use version 4.0.7

**Comment by stanuku** [comment]
@diegobrum 4.0.7 worked!, thank you.
