### ISSUE TITLE
Better way to add default parameters to search

### ISSUE THREAD

**Issue by diegobrum** [solr-express/solr-express#176]
**What?**
Drop class *SystemParameter* and add default parameters in *SolrSearch* class, *Execute* method.

**Why?**
Avoid errors like (#174)

**What it´s necessary?**
Create below parameters:
- [x] EchoParams
- [x] WriteType (generated *wt*)
- [x] Indent
- [x] Query Parser (generated *defType*)
- [x] Standard query (generated *q.alt*)
- [x] Default field (generated *df*)

**Comment by stanuku** [comment]
@diegobrum: I'm having issues with the BaseSystemParameter. Especially ["defType"] = "edismax". This is hard coded to use edismax. The edismax is not giving desired results in my case. I'm yet to figure out a proper reason. The defType=edismax, is not working properly if I'm querying a 'string' type field. It works fine with 'text' type fields in my Schema.
But, in any case, the calling function should have freedom to set or override the defType. so, I would not set set it to edismax, rather I would set it to standard query parser "lucene" or even better just not include it by default.

**Comment by diegobrum** [comment]
@stanuku 
I think then comment these lines is not a good long term solution.
The idea of this issue is drop SystemParameter and create options to add parameters using Fluent API (like code sample#1), but I plan do this in v4.2.

In your case, you can bypass this problem like the code sample#2.

---
### Sample#1
```csharp
var select = techProducts
    .Select()
    .QueryParser(QueryParser.Edismax)
    .StandardQuery("*:*")
    .DefaultField(q => q.Id)
```
---
### Sample#2
```csharp
ISolrSearch<ProjectDocument> select = _projects
	.Select()
	.Any("defType", "dismax") // <- Add this line
	.Fields(pd => pd.ProjectId)
	.Query(combinedQuery)
	.Offset(offset)
	.Limit(limit);
```

**Comment by stanuku** [comment]
@diegobrum: Sample#2 helped thank you, I did .Any("defType", "lucene").

**Comment by stanuku** [comment]
@diegobrum: I agree with your long term fluent like API for the system params.

**Comment by UncleZen** [comment]
Hi @diegobrum 

Here is a possible solution to the issue #176: https://github.com/UncleZen/solr-express/commit/67e8733de6084a9e56934e8d3bc0ddd4940e0cd3. Please have a look and let me know what you think.

The  core search parameters can be specified as GlobalParamters (which would be the case most of the time), but they can also be overridden when necessary:

```
var options = new SolrExpressOptions()
{
	GlobalParameters = { new CoreQueryParameter() { Name = CoreQueryParameterType.WriteType, Value = "xml" },
		new CoreQueryParameter() { Name = CoreQueryParameterType.QueryParser, Value = "edismax" },
		new CoreQueryParameter() { Name = CoreQueryParameterType.FieldList, Value = "" },
	}
};

var services = new ServiceCollection().AddSolrExpress<ReadOnlyDocument>(builder => builder
	.UseOptions(options)
	.UseHostAddress("http://devsolr/solr/testinstance")
	.UseSolr5()
);

var serviceProvider = services.BuildServiceProvider();
var docs = serviceProvider.GetRequiredService<DocumentCollection<ReadOnlyDocument>>();

var qry = docs
		.Select()
		.Fields(d => d.Id, d => d.DepartmentId)
		.CoreParameter(CoreQueryParameterType.WriteType, "json")

```

More members can be added to the enum CoreQueryParameterType as needed...

Cheers!

Zen

**Comment by diegobrum** [comment]
Hi @UncleZen !

I thought something more simple.

Maybe likes (solr-express\src\SolrExpress\Search\DocumentSearch.cs[78])  works well, because the issue (create default parameters) will be achieved and if somebody needs to use other values in this parameters, the feature will be already available to use.

What do you think? 

Cheers!

**Comment by UncleZen** [comment]
Hey @diegobrum, 

I am sorry I have been away last week with very little access to internet. I will look into this today and get back to you with an alternate solution.

Thanks!

Zen

**Comment by UncleZen** [comment]
Hey @diegobrum 

Following up on your suggestion, I added a method to the [DocumentSearch type](https://github.com/UncleZen/solr-express/blob/v.5.0/src/SolrExpress/Search/DocumentSearch.cs) that sets the default core query parameters. Here is the [latest commit](https://github.com/UncleZen/solr-express/commit/9d45ccdcd226e3e68b567cc68a0f34254a62dfaa).

If you agree with this approach please let me know and I will issue a pull request.

Cheers!

Zen

**Comment by diegobrum** [comment]
Hi @UncleZen !

Sorry for delay

I think this approach is more complex than necessary.

You had created a new interface and classes to create default parameters (like qt with value "edismax"), but, if I want to use another qt?

I think than this approach can be used to set values to EchoParams and Indentation (to reduce json weight) and WriteType (to return a json) , but not to others parameters.

To parameters FieldList (for example), I think is better create a implementation following the same approach of OffsetParameter and than add this parameter with a default value if user didn't do this in our code.

What do you think?

PS: I saw your implemention about facet.prefix feature. Nice job ^^

**Comment by UncleZen** [comment]
Hey @diegobrum,

I will get back to you on this in couple of days max as I am working on something else right now not related to SolrExpress...

Cheers!

Zen

**Comment by UncleZen** [comment]
Hey @diegobrum,

It has been quite busy around here. That's why it took me a bit longer than couple of days :) to get back to  you.

The default values of core  parameters can be changed in different ways:

Globally:
```
var options = new SolrExpressOptions()
{
	GlobalParameters = { new CoreQueryParameter() { Name = CoreQueryParameterType.WriteType, Value = "xml" },
		new CoreQueryParameter() { Name = CoreQueryParameterType.QueryParser, Value = "some_other_value" },
		new CoreQueryParameter() { Name = CoreQueryParameterType.FieldList, Value = "" },
	}
};

var services = new ServiceCollection().AddSolrExpress<ReadOnlyDocument>(builder => builder
	.UseOptions(options)
	.UseHostAddress("http://infomediadev/solr/newsdesk")
	.UseSolr5()
);
```

Or for a particular search:
```
var qry = docs
		.Select()
		.Fields(d => d.Id, d => d.DepartmentId)
		.CoreParameter(CoreQueryParameterType.WriteType, "xml");
```

As far as field list (fl) parameter is concerned it has to be set to empty string. Otherwise, based on my tests, the **fields** parameter generated by `FieldsParameter `class will not have any effect whatsoever. 

As far as the method `DocumentSearch.SetDefaultCoreParameters()` is concerned, I must say that I would set the default values **only** for the parameters **fl** (because as I said we have to), **wt** (because we expect JSON), **indent** and **echoParams** (for obvious reasons). The rest can be set either in solrconfig.xml file or as shown above if necessary.

This is not a perfect solution either, because when we discover that some other core parameter is needed we would have to change the enum `CoreQueryParameterType` :(.

Please let me know what you think.

**Comment by diegobrum** [comment]
Hi @UncleZen 

I agree about your general idea, but, I think this implmentation is more complex than necessary.

If you create classes to each default parameter instead of create a DefaultParameter (like below)

``` csharp
/// <summary>
/// Signatures to use wt parameter
/// </summary>
public interface IWriteTypeParameter : ISearchParameter
...

public class WriteTypeParameter : IWriteTypeParameter, ISearchItemExecution<JObject>
...
```

Then, add by default some of that parameters (like https://github.com/solr-express/solr-express/blob/v.5.0/src/SolrExpress/Search/DocumentSearch.cs#L75)

What do you think?
