### ISSUE TITLE
Support for .NET Core 1.0.1 (1.1) and higher

### ISSUE THREAD

**Issue by stanuku** [solr-express/solr-express#177]
@diegobrum:

Problem:

- In my solution, I've a ASP.NET Core 1.0.1 application (targeting full .Net 4.6.2). 
- In the same solution I've a class library project (.NET 4.6.2), this class library has my search service  implementation. 
- To this class library project I've added the SolrExpress5 package. 
- To the web app references the class library project. 
- When I run the application, it fails with the System.IO.FileLoadexception for Microsoft.Extensions.DependencyInjection.Abstractions 1.0.1. (and SolrExpress uses 1.0.0)

**Work around:**
- I upgrade the Microsoft.Extensions.DependencyInjection.Abstractions, Microsoft.Extensions.DependencyInjection packages in my Class library project to 1.0.1 
- Add a runtime binding redirect in the app.config for the Web.app to these to assemblies, it works fine.

Fix (?): Are there plans to support .NET Core 1.0.1 (1.1) and higher or you should consider it soon. 

Thanks

**Comment by diegobrum** [comment]
Hi @stanuku !

I created a issue to check these assemblies (#178).

Just by curiosity, why use .Net framework 4.6.2 and not .Net Standard??? Some mistake in Solr Express??

**Comment by stanuku** [comment]
@diegobrum I'm not totally clear on the distinction and advantages of 4.6.2 over .NET Standard yet. I'm reading yup. I have a solution that has ASP.NET Core web project and an **existing** .NET 4.6.2 class library project that I'm making use in the ASP.NET Core web project. Not yet if I should port the class library project to .NET standard. This library is a used by other applications that are in production targeting 4.6.2 .
Not sure what the implication ares...

**Comment by stanuku** [comment]
@diegobrum The main issue here is that the latest LTS patch for .NET Core 1.0.* which is. 1.0.**3** is relesed on DEC 12th. Some dependencies that you have for SolrExpress are 1.0.0. If you have a separate project for Solr search using SolrExpress and then reference that project in the Main web app project (> 1.0.0) then the dlls in bin get overwritten during build from the class library projects build output.

**Comment by diegobrum** [comment]
@stanuku Understood
I need create this scenery to confirm my suspicion about this case.

Anyway, I think this occur because, in .Net Core, I had referenced to Microsoft.Extensions.DependencyInjection.Abstractions, Microsoft.Extensions.Options and System.Net.Requests, but I think that the correct is to reference to NETStandard.Library direct to make local build process choice correct assemblies.

**Comment by stanuku** [comment]
@diegobrum: I can try to help you with the fix, if you could guide me just a bit. Are you planning to fix this in your next version?

**Comment by diegobrum** [comment]
@stanuku If you help-me, I can fix this in next version :)

Try to clone **v-4.1 branch** and change *project.json files* from *SolrExpress.Core*, *SolrExpress.Solr4* and *SolrExpress.Solr5* changing dependencies in *netcoreapp1.0* group to *NETStandard.Library* (version 1)

And after this, build your project to see if your workaround continues necessary

**Comment by stanuku** [comment]
@diegobrum Ok, will try.

**Comment by diegobrum** [comment]
Hi @stanuku !
Some news about this issue?

**Comment by diegobrum** [comment]
Hi @stanuku 

Please, check v4.1

**Comment by stanuku** [comment]
@diegobrum: Please see #186

**Comment by diegobrum** [comment]
Hi @stanuku , please take a look in v5
