### ISSUE TITLE
ISolrSearchExtensions.FacetRange

### ISSUE THREAD

**Issue by borgotecnologia** [solr-express/solr-express#180]
In method mentioned above, does not have support to remove "past dates" . 

What happens: 
Even requested period like : .FacetRange(nameof(_jobDocument.VagaDataDeCadastro), q => q.VagaDataDeCadastro, "+7DAY", "NOW/DAY-28DAYS", "NOW/DAY+1DAY"); 

The responsed json formed have facet yet. 

I need some enum options to solr not calculate any facet when do not have any data in informed period.

**Comment by diegobrum** [comment]
See #184
