### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by adback03** [solr-express/solr-express#181]
I couldn't seem to find any examples on how one would use basic auth when making requests? Is this supported?

Edit: Forgot to mention, this is using Solr5 for .NET Core

**Comment by diegobrum** [comment]
Hi @adback03 
Do you mean this feature (https://cwiki.apache.org/confluence/display/solr/Basic+Authentication+Plugin)???

**Comment by adback03** [comment]
Well I'm coming from SolrNet, and I was able to do something like this: http://www.nzederr.net/dev/2015/08/29/SolrNet-Basic-Auth.html

Basically, with each web request to solr, I'd like to attach the Basic Auth headers along with the request.

**Comment by diegobrum** [comment]
Well... it's not supported, yet :)
But I can do this in a future release (probably 4.2)

**Comment by adback03** [comment]
Sounds good! Unfortunately I'll have use alternative methods for now (probably just via RestSharp), but I'll keep an eye on v4.2.

**Comment by diegobrum** [comment]
@adback03 Please, use v.4.2.0
