### ISSUE TITLE
New way to translate queries to Solr 4/5/6

### ISSUE THREAD

**Issue by diegobrum** [solr-express/solr-express#190]
- **Goals**
 1. Less code
 2. Less unit test
 3. Easier to understand
 4. Easier to create new parsers

**Comment by diegobrum** [comment]
@stanuku Brain storm

Today, to translate C# objects to SOLR queries, I use interfaces in core package and implementation in SOLR4/5 packages... I think it's a good approach, but generate a lot of redundant code and unit tests and BaseClasses.

What do you think about?

**Comment by stanuku** [comment]
@diegobrum: I'll think more about it, but I have a general question, do you want to support Solr 4? Solr 5 has been around for almost 2 years now.

**Comment by diegobrum** [comment]
@stanuku Solr4, yes for now

But, if Solr 6 have some exclusive feature, I need some way to do this without impact Solr 5

**Comment by stanuku** [comment]
@diegobrum: Yes, correct.
