### ISSUE TITLE
FieldList in solr5

### ISSUE THREAD

**Issue by hheexx** [solr-express/solr-express#192]
How can I project data in solr5?

I see there is FieldList parameter in solr4 that adds fl to the query but I don't see it in solr5

Is it missing or is there another way?

**Comment by diegobrum** [comment]
Hi @hheexx 

Use ***Fields*** method like below code:
``` csharp
documentCollection
 .Select()
 .FIelds(q => q.Field1, q => q.Field2);
```

---
Se more in http://solr-express.readthedocs.io/en/4.1.1/tutorials/getting-started and http://solr-express.readthedocs.io/en/4.1.1/api/use-cases/

**Comment by hheexx** [comment]
Hi @diegobrum !! 

I tried but it's not working.
I'm trying now to find a way to see generated query to check.

I think it would be great if you you can add ISolrQuery.ToString() to display generated query.

**Comment by diegobrum** [comment]
To see generated query, just do:

```
var log = new SimpleLogInConsoleQueryInterceptor(); // <- Query interceptor used to log purpose

documentCollection
 .Select()
 .Fields(q => q.Field1, q => q.Field2)
 .Add(log)
 .Execute();

var x = log.Query; // <- Query string sent to SOLR (case using Solr4) or JSON object sent to SOLR (case using Solr5/6)
```

**Comment by hheexx** [comment]
Nice!
Please consiter toString() also, it is much more intuitive and convinient.

I checked the query, it sends fields array so it's probably problem with solr configuration.

Beautiful lib by the way :)

**Comment by hheexx** [comment]
@diegobrum 

Are you sure you should be sending 'fields' param and not 'fl'?

When I change fileds to fl it works.

I can't find anywhere in SOLR documentation that that field changed name in solr5.

**Comment by diegobrum** [comment]
In Solr 5, I have a new feature called **JSON Request API** (see http://yonik.com/solr-json-request-api/ and https://cwiki.apache.org/confluence/display/solr/JSON+Request+API) and because this I can send a JSON in body request using a query like *{ fields: ['field1', 'field2'] }*

Please, give me some information:

- Solr Express version
- Solr version
- Using package Solr4 or Solr5?

**Comment by hheexx** [comment]
Solr 6.3.0
Express 4.1.0
Solr5

**Comment by hheexx** [comment]
When I create query like this in solr admin interface (JSON):
```
"params":{
      "q":"*:*",
      "df":"propId",
      "indent":"on",
      "fl":"location",
      "wt":"json",
      "_":"1484665074043"}}
```
It works.
When I change fl to fields it does not.

**Comment by diegobrum** [comment]
Can you show me the query generated by SolrExpress ??

**Comment by hheexx** [comment]
```
[SimpleLogQueryInterceptor] 2017-01-17 17.06.44.+01:00
{
  "limit": 9999,
  "fields": [
    "propId",
    "location"
  ],
  "params": {
    "echoParams": "none",
    "wt": "json",
    "indent": "off",
    "defType": "edismax",
    "q.alt": "*:*",
    "df": "id"
  },
  "query": "*:*",
  "sort": "score desc",
  "offset": 0
}
```

**Comment by diegobrum** [comment]
In Solr Admin UI, try pass in *Raw Parameter* follow query:

``` json
json={"limit": 9999,"fields": ["propId","location"],"params": {"echoParams": "none","wt": "json","indent": "off","defType": "edismax","q.alt": "*:*","df": "id"},"query": "*:*","sort": "score desc","offset": 0}
```
---

Is it works?

**Comment by hheexx** [comment]
It does not.
But when I enter it in raw parameters it ends up in params object.

**Comment by diegobrum** [comment]
@hheexx 
See my test case settings and tell-me what is different in your case

### Using

- Solr 6.3.0
- SolrExpress 4.1.1
- Using package Solr5
- Console App using Net core 1.0 and Microsoft.NETCore.App v1.0.1
- Collection *TechProducts* using this instructions (https://github.com/solr-express/solr-express/tree/master/test/SolrExpress.Solr5.IntegrationTests)

---

### Startup.cs config

``` csharp
serviceCollection.AddSolrExpress<TechProduct>(builder => builder
 .UseHostAddress("http://localhost:8983/solr/techproducts")
 .UseSolr5());
```

---

### Test

``` csharp
var serviceProvider = serviceCollection.BuildServiceProvider();
var techProducts = serviceProvider.GetRequiredService<IDocumentCollection<TechProduct>>();
IEnumerable<TechProduct> documents;

var select = techProducts
 Select()
 .Add(log)
 .Fields(q => q.Id, q => q.Manufacturer)
 .QueryAll()
 .Limit(3)
 .Execute()
 .Document(out documents);
```

### JSON sent to SOLR

``` json
{
  "fields": [
    "id",
    "manu"
  ],
  "params": {
    "echoParams": "none",
    "wt": "json",
    "indent": "off",
    "defType": "edismax",
    "q.alt": "*:*",
    "df": "id"
  },
  "query": "*:*",
  "sort": "score desc",
  "offset": 0,
  "limit": 3
}
```

### Response from SOLR

``` json
{
    "responseHeader": {
        "status": 0,
        "QTime": 0
    },
    "response": {
        "numFound": 32,
        "start": 0,
        "docs": [
            {
                "id": "GB18030TEST"
            },
            {
                "id": "SP2514N",
                "manu": "Samsung Electronics Co. Ltd."
            },
            {
                "id": "6H500F0",
                "manu": "Maxtor Corp."
            }
        ]
    }
}
```

**Comment by hheexx** [comment]
I will first check my solrconfig and compare it with current example.

**Comment by diegobrum** [comment]
@hheexx Any news about issue?

**Comment by stanuku** [comment]
@hheexx: It should work as @diegobrum suggested for Solr5. I'm doing that in my application.

You could also try Fiddler to capture and compose new JSON request payload to the /select handler in Solr.

**Comment by hheexx** [comment]
I ported some configuration from example solrconfig.xml to my config because my config is copied from earlier solr versions (3X)
I copied anything that mesions JSON but still no luck.
I didn't find explicit configuration for JSON API anywhere.

I'm still looking around...

**Comment by diegobrum** [comment]
@hheexx JSON Request API was implemented in Solr 5.1
Take a look in below links, maybe help you :)

http://archive.apache.org/dist/lucene/solr/5.1.0/changes/Changes.html#v5.1.0.new_features
https://issues.apache.org/jira/browse/SOLR-7214
https://issues.apache.org/jira/browse/SOLR-7216

**Comment by hheexx** [comment]
@diegobrum 
Now I tried my query above from curl and it works. Returns just required fields.
I pasted query directly from SimpleLogQueryInterceptor to curl and in curl it works but solr-express returns full result object.
Does this make any sense to you?

**Comment by diegobrum** [comment]
@hheexx 
If you use code below, you give a IEnumerable<TDocument> with each instance of TDocument filled only with Id and Manufacturer properties

``` csharp
var serviceProvider = serviceCollection.BuildServiceProvider();
var techProducts = serviceProvider.GetRequiredService<IDocumentCollection<TechProduct>>();
IEnumerable<TechProduct> documents;

var select = techProducts
 Select()
 .Fields(q => q.Id, q => q.Manufacturer)
 .Execute()
 .Document(out documents); // <- List with TechProducts

// documents[0].Id != Null
// documents[0].Categories = Null
```
---

Is it your case???

**Comment by diegobrum** [comment]
Closing for lack of new information
