### ISSUE TITLE
Question - Dynamic list of filters

### ISSUE THREAD

**Issue by TheFairey** [solr-express/solr-express#202]
Hi

Apologies but my C# isn't great and I'm struggling to work how I build a dynamic filter object to pass to Filter() say I have multiple fields they might filter on but some aren't always set so trying to work out how I build a dynamic filter that contains all the filters selected.

If you have an example somewhere that does this I can probably work it out from there?

Much appreciated.

Thanks

Si

**Comment by diegobrum** [comment]
Hi @TheFairey 

I don't know if I undestand correctily your question, but take a look in bellow code (that code "transpiles" string provided by some URI in SolrExpress notation).

``` csharp
// Url sent to API
var someUrl = "MyProperty1=Some value&MyProperty2=Another value";

// Parameters splitted from url
var args = someUrl
    .Split('&')
    .Select(q => q.Split('='))
    .ToDictionary(k => k[0].ToLower(), v => v[1]);

// Possible filters
var model = new MyDocument();
var filters = new Dictionary<string, Expression<Func<MyDocument, object>>>
{
    { nameof(model.MyProperty1).ToLower(), (q) => q.MyProperty1 },
    { nameof(model.MyProperty2).ToLower(), (q) => q.MyProperty2 }
};

// args
foreach (var arg in args)
{
    if (filters.ContainsKey(arg.Key))
    {
        solrContext
            .Filter(filterToRegion, $"\"{value}\"");
    }
}
```

**Comment by TheFairey** [comment]
Hi

Thanks for getting back to me and sorry for the delayed reply been rather busy! I tried what you suggested but think there is a bit missing as it doesn't like the mysearch.Filter line

        static void Main(string[] args)
        {
            IDocumentCollection<MyDoc> mysearch = new DocumentCollectionBuilder<MyDoc>()
                .AddSolrExpress()
                .UseHostAddress("http://mysearchurl")
                .UseSolr4()
                .Create();

            IEnumerable<MyDoc> documents;
            Information statistics;
            IEnumerable<FacetKeyValue<string>> facetFieldList;

            string[] persons = new string[] { "Alison*", "Greg*" };

            var model = new MyDoc();
            var filters = new Dictionary<string, Expression<Func<MyDoc, object>>>
            {
                { nameof(model.Person).ToLower(), (q) => q.Person }
            };

            foreach (var person in persons)
            {
                // Compiler doesn't like this
                mysearch.Filter(filters["person"], $"{person}");
            }

            try
            {
                mysearch.Select()
                        .Any("qt", "search")
                        .Any("df", "text")
                        .Query("*:*")
                        .Limit(10)
                        //.Filter(d => d.Person, "Alison*")
                        //.Filter(d => d.Person, "Greg*")
                        .Execute()
                        .Document(out documents)
                        .Information(out statistics)
                        .FacetField(out facetFieldList);
            }catch(Exception e)
            {
                Console.WriteLine(e.ToString());
            }
        }

Wondering what I've got wrong? Compiler error is:
    Error	CS1929	'IDocumentCollection<MyDoc>' does not contain a definition for 'Filter' and the best extension method overload 'ISolrSearchExtensions.Filter<MyDoc>(ISolrSearch<MyDoc>, Expression<Func<MyDoc, object>>, string, string)' requires a receiver of type 'ISolrSearch<MyDoc>'

Cheers

Si

**Comment by diegobrum** [comment]
Hi @TheFairey !

Try this

```
  var mySelect = mysearch
    .Select()
    .Any("qt", "search")
    .Any("df", "text")
    .Query("*:*")
    .Limit(10);

  foreach (var person in persons)
  {
    // Compiler now likes this :D
    mySelect.Filter(filters["person"], $"{person}");
  }

  try
  {
    mySelect
      .Execute()
      .Document(out documents)
      .Information(out statistics)
      .FacetField(out facetFieldList);
  }
  catch(Exception e)
  {
    Console.WriteLine(e.ToString());
  }
```

**Comment by TheFairey** [comment]
@diegobrum Perfect thanks, now I can work out adding my other filters and then just waiting on highlighting :-)

Cheers

Si
