### ISSUE TITLE
Under load solr-express hangs the kestrel 

### ISSUE THREAD

**Issue by hheexx** [solr-express/solr-express#205]
Hi,

We released site to production and we have hangs most probably caused by solr-express.
I am investigating and I hope I will have more info soon.

Does solr express have any configurable timeout option?

**Comment by diegobrum** [comment]
Hi @hheexx 

Sad read about that: '(

No, SolrExpress doesn't have any configuration to timeout. But, what you need? Timeout in connection with Solr Server?

And any information about your pain will be great to find errors in SolrExpress project :)

**Comment by diegobrum** [comment]
I can create connection timeout settings, but, only in v5.1

**Comment by hheexx** [comment]
5.0 soon?
Dont forget minCount :)

**Comment by diegobrum** [comment]
Yes, soon :)
Yes, minCount :)

**Comment by hheexx** [comment]
Hi @diegobrum 

I have a lot of threads in this position:

```
Not Flagged	>	20152	0	Worker Thread	Worker Thread	System.Private.CoreLib.ni.dll!System.Threading.ManualResetEventSlim.Wait	Normal
 	 	 	 	 	 	[Managed to Native Transition]	 
 	 	 	 	 	 	System.Private.CoreLib.ni.dll!System.Threading.ManualResetEventSlim.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	 
 	 	 	 	 	 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.SpinThenBlockingWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	 
 	 	 	 	 	 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.InternalWait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	 
 	 	 	 	 	 	System.Private.CoreLib.ni.dll!System.Threading.Tasks.Task.Wait(int millisecondsTimeout, System.Threading.CancellationToken cancellationToken)	 
 	 	 	 	 	 	SolrExpress.Solr5.dll!SolrExpress.Solr5.SolrConnection.Get(SolrExpress.Core.SecurityOptions options, string handler, string data)	 
 	 	 	 	 	 	SolrExpress.Core.dll!SolrExpress.Core.Search.SolrSearch<CxPublic.Models.SolrModel>.Execute()	 
 	 	 	 	 	 	cx_public.dll!CxPublic.Controllers.SearchMapController.Get(Newtonsoft.Json.Linq.JObject json)	
```

Looks like deadlock in on trying to get solr connection.
Does that make sense? Can you investigate?

**Comment by hheexx** [comment]
I have improved the situation with switching from flurl to .nets httpclient.
But deadlocks are still happening.
I think it's related to using async API (httpclient) synchronously.

Do you plan to offer async version of solr-express?

**Comment by diegobrum** [comment]
Hum... interesting

Yes, I plan (#161), but only after I create new code base (#187)

**Comment by diegobrum** [comment]
Hi @hheexx , try v5
