### ISSUE TITLE
Facet prefix parameter

### ISSUE THREAD

**Issue by UncleZen** [solr-express/solr-express#206]
Is there a way to specify the facet prefix for a facet field? See: https://cwiki.apache.org/confluence/display/solr/Faceting#Faceting-Thefacet.prefixParameter

Btw. @diegobrum great work. Thanks for all your efforts.

**Comment by diegobrum** [comment]
Hi @UncleZen 

Tks a lot.

In current version and using fluent api, no :/

But, you can do this (ungly, but works):

```csharp
.Any("f.<fieldname>.facet.prefix", "some-prefix")
```

**Comment by UncleZen** [comment]
Hi @diegobrum 

Thank you very much for such a quick response. 

I have been working for quite some time on a project that uses Solr and SolrNet as .NET query library. SolrNet did suit our needs perfectly fine, but now that we are converting this application to ASP.NET Core we can no longer use it. Therefore, we decided to go for Solr-Express, which we love so far. This is to give you some context as to why I decided to fork your project and and fix the issue with facet constraints prefix by changing the interface IFacetFieldParameter<TDocument> and some other classes (https://github.com/UncleZen/solr-express).    

If you'd like to include these changes in your project, please let me know so that I can issue a Pull Request at any time. 

Next, we need  to tackle the Solr Dynamic Fields (https://wiki.apache.org/solr/SchemaXml#Dynamic_fields). I have a pretty good idea how to make it work in Solr-Express and I should be able to push this changes to GitHub pretty soon. I'll keep you updated. If you agree, we would love to contribute to your project.


Cheers!

Zen

**Comment by diegobrum** [comment]
Hi @UncleZen 

Happy to ready about this. Of course I agree with your contribution 😄 

I'm had created a new branch (called v5) to simplify project's code base, improve performance, create better DI packages and other stuffs (more details in #187), take a look in this branch, some things like **facet.prefix** (https://github.com/solr-express/solr-express/commit/ab2cd575c58729e53048385dd5e1685f03760988) and **value InList** (https://github.com/solr-express/solr-express/commit/ea354b352a85cf51b96d4d56fecc9517edf07b52) is easier to do in this new code base.

About dynamic fields, what's your thoughts?

**Comment by UncleZen** [comment]
Ok then. I will fork the v5 branch later in the evening and add these changes to the newly created fork. I will let you know when done.

As far as the dynamic fields are concerned, below is my solution that works fine for us:

- Add two properties to the `IFieldsParameter<TDocument>` interface (`string FieldSuffix { get; }` and `string FieldPrefix { get; }`).
- Change the signature of `IFieldsParameter<TDocument>Configure` method to: `IFieldsParameter<TDocument> Configure(string prefix, string suffix, params Expression<Func<TDocument, object>>[] expressions)`
- Change the `FieldsParameter<TDocument>.Execute` method to take into consideration the field prefixes and suffixes like this:

```
public void Execute(JObject jObject)
{
    var jArray = (JArray)jObject["fields"] ?? new JArray();

    if (Expressions != null)
	{
		foreach (var expression in Expressions)
		{
			var fieldName = this._expressionBuilder.GetFieldNameFromExpression(expression);

			if (fieldName.StartsWith("_"))
			{
				jArray.Add($"{Suffix}{fieldName}");
			}
			else if (fieldName.EndsWith("_"))
			{
				jArray.Add($"{fieldName}{Suffix}");
			}
			else
			{
				jArray.Add(fieldName);
			}	
		}
	}
	jObject["fields"] = jArray;
}
```

- Change `ISolrSearchExtensions.Fields` extension method accordingly etc...

As you can see the field prefix and suffix is global to all dynamic fields for the current search, which works fine the way we use dynamic fields (I have tested and it works fine). This solution however, would an issue if the prefix/suffix is not the same across all fields. In such a case we would have to come up with a different solution. One solution that comes to my mind could be to change the signature of the `IFieldsParameter<TDocument>.Configure` method to let's say: `IFieldsParameter<TDocument> Configure(string suffix, params Expression<Func<TDocument, Tuple<object, IDynamicParamterAddition>>>[] expressions);`...

Let me know what you think.

**Comment by diegobrum** [comment]
Good approach, but I have some considerations:

* I think than a minor percent of people use dynamic fields (I don't have data to affirm with 100% sure, I only have a feeling about this).
* Create a conplexity solution to create a change to use dynamic fields thinking in a global suffix/prefix or in case-to-case suffix/prefix.

I don't feel comfortable to change signatures in pro to a minor user share.

Maybe a another approach.. What do think about use **SolrFieldAttribute** to do this work?

* Add 3 properties in Attribute. ```bool IsDynamicField```, ```string DynamicFieldPrefixName```, ```string DynamicFieldSuffixName```
* Add 2 properties in GlobalSettings. ```string GlobalDynamicFieldPrefixName```, ```string GlobalDynamicFieldSuffixName```
* Change the `FieldsParameter<TDocument>.Execute` method to take into consideration the field prefixes and suffixes like this:

``` csharp
private readonlye SolrExpressSettings _solrExpressSettings;

public void Execute(JObject jObject)
{
    var jArray = (JArray)jObject["fields"] ?? new JArray();

    if (Expressions != null)
	{
		foreach (var expression in Expressions)
		{
			var dynamicSettings = this._expressionBuilder.GetFieldDyanamicSettingsFromExpression(expression);
			var fieldName = this._expressionBuilder.GetFieldNameFromExpression(expression);

			if (dynamicSettings.IsDynamicField)
			{
				prefix = dynamicSettings.DynamicFieldPrefixName ?? this._solrExpressSettings.GlobalDynamicFieldPrefixName;
				suffix = dynamicSettings.DynamicFieldSuffixName ?? this._solrExpressSettings.GlobalDynamicFieldSuffixName;
				fieldName = $"{prefix}{fieldName}{suffix}";
			}

			jArray.Add(fieldName);
		}
	}
	jObject["fields"] = jArray;
}
```

In your approach, I like clean code, use fluent API and make things easy to understand, but increase complexity.
In my approach, I like simple code, but increase *automagically* in code.

What do you think?

Happy Easter! / Joyeuses Pâques!

**Comment by UncleZen** [comment]
This is a very good (nice and clean) solution. It would, however, work only in cases when field prefix/suffix is a constant. In our app this approach would not work because the suffix varies and depends on the organization context. I will try to explain what I mean with this, in the example below :

Let's say we receive the article https://blogs.windows.com/buildingapps/2017/04/05/windows-10-creators-update-creators-update-sdk-released. Before we store it in Solr we filter it. Basically we try to find keyword matches based on settings of each organization that has signed up with our web app. 

E.g. for Organization A (Id: 52) keyword hits would be  "Win 32 apps" and "Bluetooth device" and we store this in the dynamic field keywordhits_5=["Win 32 apps", "Bluetooth device"].
For Organization B (Id: 32) based on their settings we find a completely different set of matches: "Surface Dial", "XBox" and "HoloLens". This set of matches will be stored in the field keywordhits_32 = ["Surface Dial", "XBox", "HoloLens"].

So when a user views the this article in the context of the Organization A (http://myapp.com/org-a/article/some-article-id) they will see Win 32 apps and Bluetooth device highlighted. When they view the same article in the context of the Organization B (http://myapp.com/org-b/article/some-article-id) the corresponding keywords hits will be highlighted. 

With other words, the suffix or prefix has to be specified  at the time when the search is performed and based on the organization context.

Cheers!

Zen

**Comment by diegobrum** [comment]
Wow! Complex, isn't? 😄 

Ok... hum... maybe a mix in approaches.

What do you think in add some method in Search to control this case? Like this:

# Approch

1. Add 3 properties in Attribute. ```bool IsDynamicField```, ```string DynamicFieldPrefixName```, ```string DynamicFieldSuffixName```
2. Add 2 properties in GlobalSettings. ```string GlobalDynamicFieldPrefixName```, ```string GlobalDynamicFieldSuffixName```
3. Create a new Parser (to customize field settings) with 3 properties ```Expression Field```, ```string DynamicFieldPrefixName```, ```string DynamicFieldSuffixName```
4. Change the `FieldsParameter<TDocument>.Execute` method to take into consideration the field prefixes and suffixes like this:

``` csharp
private readonlye SolrExpressSettings _solrExpressSettings;

public void Execute(JObject jObject)
{
    var jArray = (JArray)jObject["fields"] ?? new JArray();

    if (Expressions != null)
	{
		foreach (var expression in Expressions)
		{
			// GetFieldSettingsFromExpression merges settings from SolrFieldAttribute and some custom settings provided by item#3 in list above
			var fieldSettings = this._expressionBuilder.GetFieldSettingsFromExpression(expression);
			var fieldName = fieldSettings.Name;

			if (fieldSettings.IsDynamicField)
			{
				prefix = fieldSettings.DynamicFieldPrefixName ?? this._solrExpressSettings.GlobalDynamicFieldPrefixName;
				suffix = fieldSettings.DynamicFieldSuffixName ?? this._solrExpressSettings.GlobalDynamicFieldSuffixName;
				fieldName = $"{prefix}{fieldName}{suffix}";
			}

			jArray.Add(fieldName);
		}
	}
	jObject["fields"] = jArray;
}
```
# Considerations
* If developer only needs to use dynamic fields using global prefix and suffix names, itens 1 and 4 works well
* If developer only needs to use dynamic fields using specific prefix and suffix names by field, itens 1, 2 and 4 works well
* Finally, in your case, itens 1, 3 and 4 works well

---

What do you think?

**Comment by UncleZen** [comment]
Yeah, a bit complex indeed. 

I agree with your solution as it allows the developers to choose the least complex approach that suits their needs. I will be working on this in the coming days. I'll keep you updated.

**Comment by UncleZen** [comment]
Hi @diegobrum,

I am using the branch v.5.0 to run a very simple query in a .NET Core Console app. See code below:

```
IServiceCollection services = new ServiceCollection();

var options = new SolrExpressOptions();

services = services.AddSolrExpress<ReadOnlyDocument>(builder => builder
.UseHostAddress("http://infomediadev/solr/newsdesk")
.UseSolr5()
);

var serviceProvider = services.BuildServiceProvider();

var docs = serviceProvider
			   .GetRequiredService<DocumentSearch<ReadOnlyDocument>>();

IEnumerable<ReadOnlyDocument> documents;
IEnumerable<FacetKeyValue> facets;
Information information;

var qry = docs
	.Fields(d => d.Id, d => d.Title, d => d.DepartmentId)
	.FacetField(d => d.Categories)
	.Filter(d => d.Id, "205325092");

qry.Execute()
	.Information(out information)
	.Document(out documents)
	.Facets(out facets);


foreach (var document in documents)
{
	Console.WriteLine($"{document.Id} => {document.Title}");

	foreach (var deptId in document.DepartmentId)
	{
		Console.WriteLine($"{deptId}");
	}

}
```

But for some reason it is complaining that DocumentSearch type has not been registered. Any ideas?  

As well, is there an implementation for the interface ISearchItemCollection? 

Thanks!

Zen

**Comment by diegobrum** [comment]
Hi @UncleZen 

Sorry for late

Please, get code again and check https://github.com/solr-express/solr-express/blob/v.5.0/example/SimpleUse.NetCore/Program.cs

**Comment by UncleZen** [comment]
No problem at all. Thanks @diegobrum!

**Comment by UncleZen** [comment]
This fixed the issue. Thanks @diegobrum.

We are experiencing major issues when opening the SolrExpress solution in VS 2015.  Attached is one of the errors we get when opening the SolrExpress solution in VS 2015. The only way for us to test SolrExpress so far has been to open the solution in VS 2017 which converts all projects to csproj. The conversion usually is completed without any issues whatsoever. 

Are you planning to convert the xproj to csproj? 

Cheers!

Zen

**Comment by diegobrum** [comment]
Hi @UncleZen !

Funny, in my machine works fine :/

Btw, yes, I want to migrate to VS 2017

**Comment by UncleZen** [comment]
Thanks @diegobrum!

**Comment by diegobrum** [comment]
Hi @UncleZen , please take a look in v5

**Comment by UncleZen** [comment]
Thanks @diegobrum. I'll have a look at it soon.

Zen
