### ISSUE TITLE
Divide by Zero Errors getting Information when Limit = 0

### ISSUE THREAD

**Issue by Akaoni** [solr-express/solr-express#208]
The following line throws a divide by zero error when Limit is set to 0 (e.g. getting only Facet results):

https://github.com/solr-express/solr-express/blob/master/src/SolrExpress.Core/Search/Result/InformationBuilder.cs

Line 26: PageNumber = (offset / limit) + 1,

**Comment by diegobrum** [comment]
Hi @Akaoni  , please take a look in v5
