### ISSUE TITLE
How to do a simple search?

### ISSUE THREAD

**Issue by Baklap4** [solr-express/solr-express#213]
I've been trying to figure out how to do a in my eyes 'simple' search. 
I've uploaded a few documents with each a content field containing the data extracted from a document by using tika. 

What i want to do is create a simple contains query over every field to search for a single word.
I thought this was done by using the following:

```
IEnumerable<SolrDocument> solrDocuments;
                this.documentCollection
                    .Select()
                    .Query("Hello world")
                    .Execute()
                    .Document(out solrDocuments);
```

# question
How would i search every property of a solrdocument if it contains a simple string for example: `Hello world`?

**Comment by Baklap4** [comment]
I think i've figured it out by trial and error however this still seems very unnatural to me.
The query i'm currently using is the following:
```
IEnumerable<SolrDocument> solrDocuments;
                this.documentCollection
                    .Select()
                    .QueryField("id filepath author created last_modified title keywords content resourcename")
                    .Query($"*{filter.Search}*")
                    .Execute()
                    .Document(out solrDocuments);
```
Where in `QueryField` every field is filled in.. since it won't allow `*`
To get the contains effect i have to use wildcards like within the query method: `Query("*Hello world*")`

Is this the correct way or am i still doing something weird?

**Comment by Baklap4** [comment]
Now i'm stuck with finding a literal string.
So my document has the a sentence like the following `Heey you, how are you?`
I'm trying to do a literal match with:
```
IEnumerable<SolrDocument> solrDocuments;
                this.documentCollection
                    .Select()
                    .QueryField("id filepath author created last_modified title keywords content resourcename")
                    .Query($"\"how are you?\"")
                    .Execute()
                    .Document(out solrDocuments);
```

If i post this within solr it does give me the result, however with solr-express it doesn't...
@diegobrum

**Comment by diegobrum** [comment]
Hi @Baklap4 
Sorry for the late.


Maybe, because in SolrExpress v4, I used edismax and (probably) you use dismax. Can you test again using edismax??
