### ISSUE TITLE
Value cannot be null. Parameter name: baseUrl

### ISSUE THREAD

**Issue by artziem** [solr-express/solr-express#218]
at Flurl.Url..ctor(String baseUrl)
at SolrExpress.Solr5.SolrConnection.Get(SecurityOptions options, String handler, String data)
at SolrExpress.Core.Search.SolrSearch`1.Execute()
at ...

Config DI:

```C#
serviceCollection.AddSolrExpress<ProductResult>(builder => builder
                .UseOptions(new DocumentCollectionOptions<DocumentResult>()
                {
                    HostAddress = @"http://x.x.x.x:8983/solr/someCollection",
                    Security = new SecurityOptions()
                    {
                        AuthenticationType = AuthenticationType.Basic,
                        UserName = Configuration["Solr:User"],
                        Password = Configuration["Solr:Password"]
                    }
                })
                .UseSolr5());
```

@diegobrum
Seems like SecurityOptions and HostAddress are not include in DocumentCollectionBuilder when UseOptions.

Thanks.

**Comment by diegobrum** [comment]
Hi @artziem , please take a look in v5

**Comment by artziem** [comment]
Almost, with small exception in SolrConnection when call SetAuthentication.
Something like this work for me:

```C#
private IFlurlClient SetAuthentication(Url url)
{
	switch (this._options.Security.AuthenticationType)
	{
		case AuthenticationType.Basic:
			return url.WithBasicAuth(this._options.Security.UserName, this._options.Security.Password);
		default:
			return new FlurlClient(url, true);
	}
}

public string Get(string handler, List<string> data)
{
	//...

	return this.SetAuthentication(url)
		.GetStringAsync()
		.Result;
}

//and so on
```

**Comment by diegobrum** [comment]
Hi @artziem , please take a look in v5-Beta2

**Comment by artziem** [comment]
Thanks for quick reply and improvements.

But in previous post I'm pointed that the bug is also in **SolrConnection** class.

The methods in it doesn't set auth header. They operate on _Flurl.Url_ not _IFlurlClient_ when sending request.
Instance returned from _WithBasicAuth_ must be consumed in chainable way.

Take a look on my previously posted code with a sample solution.

**Comment by diegobrum** [comment]
Hi @artziem !

You are absolutely right!

Please, see version 5, final release

**Comment by tno2007** [comment]
Just to help anyone else out, this same exact error happens in the RestSharp.RestClient library.
