### ISSUE TITLE
Support for define local parameters?

### ISSUE THREAD

**Issue by artziem** [solr-express/solr-express#222]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Lack of control over local parameters? Or how to..

## Expected behavior
Possibility to define local parameters (in params section) and forward the query to one of them.
But together with not passing the *query* and *defType* parameters:

```json
{
  "params": {
    "userQuery": <query>,
    "echoParams": "none",
    "wt": "json",
    "indent": "off"
  },
  "sort": "score desc",
  "fields": [
    "*,score"
  ],
  "limit": 10,
  "offset": 0
}
```

Alternatively, possibility to remove *query* and *defType* parameters and ability to add custom query string parameter to url when searching.

## Use case
I have a complex query with subqueries where I'd like to pass user query:

```javascript
{
"q": "_query_:\"{!edismax qf=$qfQuery mm=$mmQuery pf=$pfQuery bq=$boostQuery v=$userQuery}\"",
"boostQuery": "_query_:\"{!edismax qf=$boostQueryQf mm=100% v=$userQuery}\"^100000"
//...
}
```

Currently written as RequestHandler in solrconfig.xml but still *userQuery* with query input must be forwarded to handler.

## Environment

- Connect to a SOLR version: 6.6.0
- Connect to a SOLR in cloud mode? [ ] Yes [x] No
- I'm coding using platform:  Windows
- Using .net version: netcoreapp1.1
- Using SolrExpress package: SolrExpress.Solr5
- Using SolrExpress package version: 5.0.0-BETA1

**Comment by diegobrum** [comment]
Hi @artziem , this issue is partially resolved in v5-BETA2.

### First part
First part of you issue is remove *defType* and other thinks.
You can do this using new options (*SetQueryParser*, *SetStandardQuery* and *SetDefaultField*), like bellow:

```csharp
services
	.AddSolrExpress<TechProduct>(builder => builder
		.UseOptions(options =>
		{
			options.SetQueryParser = false;// Don't create default parameter QueryParserParameter using value defType=edismax
			options.SetStandardQuery = false;// Don't create default parameter StandardQueryParameter using value q.alt=*:*
			options.SetDefaultField = false;// Don't create default parameter DefaultFieldParameter using value df=id
		})
		// ...  Other settings
	);
```

### Second part

For version 5, you can use *AnyParameter* and set your local variable, in this case you lost query generations and fail fast feature.
Do something like this:
```
documentCollection
	.Select()
	.Any("$userQuery", "some value here")
	// ... other parameters
	.Execute();
```

But, in v5.1 I will create a specific parameter to do this

**Comment by artziem** [comment]
Many thanks. Works like a charm, even with multiple Any.
($ sign is unnecessary in parameter definition, only when refers to param)

**Comment by diegobrum** [comment]
Hi @artziem , please check version 5.1

**Comment by artziem** [comment]
Hi @diegobrum. By 5.1 you mean nuget version 5.0.1? I'm getting an error:

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'

   at SolrExpress.Search.Parameter.Extension.ILocalParameterExtension.Name[TDocument](ILocalParameter`1 parameter, String name)
   at SolrExpress.Search.Parameter.Extension.ParametersExtension.LocalParameter[TDocument,TValue](DocumentSearch`1 documentSearch, String name, String value)
   at Project.Domain.Services.ProductService.Search(String query, Int32 resultsPerPage, Int32 pageNumber) in C:\Sources\Project\Project.Domain\Services\ProductService.cs:line 148
   at Project.Tests.Domain.Services.ProductServiceTest.Search_ExpectSuccess() in C:\Sources\Project\Project.Domain.Tests\Services\ProductServiceTest.cs:line 207
```
Usage:
```C#
var solrResultCollection = serviceProvider.GetRequiredService<DocumentCollection<ProductResult>>();
solrResultCollection
    .Select()
    .Handler("search")
    .LocalParameter<ProductResult, string>("mainQuery", query)
    .Execute()
    .Document(out IEnumerable<ProductResult> documents);
```

Probably **ILocalParameter** implementation is not register in DI container. I'm using **SolrExpress.DI.CoreClr**.

Also, it is necessary to specify type arguments on calling LocalParameter?

**Comment by diegobrum** [comment]
Hi @artziem 
Please see 5.1.1 and issue #234 

And it's not necessary to specify type arguments, this bug was fixed too :)

**Comment by artziem** [comment]
Yeah, its working now. Thanks for fixing.
