### ISSUE TITLE
fieldExpression parameter is not being used in Filter

### ISSUE THREAD

**Issue by pekic** [solr-express/solr-express#239]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Filter function in DocumentSearch has fieldExpression as a function parameter.
In [this one](https://github.com/solr-express/solr-express/blob/1ae3591294c0bb44724110b3a9802180bbfbee15/src/SolrExpress/Search/Parameter/Extension/ParametersExtension.cs#L228) it is used for filtering, [but in the other one ](https://github.com/solr-express/solr-express/blob/1ae3591294c0bb44724110b3a9802180bbfbee15/src/SolrExpress/Search/Parameter/Extension/ParametersExtension.cs#L251) it is not. Leading to that when you need to use Filter function with a query you have to specify first query.Field(filed=>field.someFieldName).

## Expected behavior
For ether fieldExpression to be used in the other Filter function or to be removed from the function signature.

**Comment by diegobrum** [comment]
@pekic , please see v5.1.2
