### ISSUE TITLE
SearchQuery prevents you from using tokenization properly

### ISSUE THREAD

**Issue by pekic** [solr-express/solr-express#240]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## Current behavior
Recently I have upgraded my project's Solr5 library from 4.2.5 to 5.1.1 and made a bunch of changes especially regarding filtering rather successfully.
However, in the previous version filtering was being used by writing my own expressions. 
Ex. search.Filter(x => x.Names, "(John AND Jack AND Mike)")
Now I am using the methods you provided with SearchQuery.
search.Filter(x => x.Names, query=> query.All(new string[] { "John", "Jack", "Mike"} ))

The problem I am facing is when I have tokens in the strings I want to search, so I want to search all the Names that start with "Jo" i would want to have "names:Jo*" for the Filter. But using any of the functions provided in SearchQuery.cs the strings I want to add to the filters have " (double quotation marks) when they are added to the filter. So the result would be for instance "names:"Jo*"" which renders the whole tokenization setup borderline useless.

The reason for all this being [AddValue](https://github.com/solr-express/solr-express/blob/29f40598ff839841a07c167c396d1cff5557dadb/src/SolrExpress/Search/Query/SearchQuery.cs#L96) function always adds your strings value with quotation marks.

Is there a way around using SearchQuery? Or am I missing some important point on how to use SearchQuery with tokenization?

**Comment by diegobrum** [comment]
Hi @pekic !

Sorry for the inconvenience

I will create a new signature to control "addQuotesInString" param in AddValue method

Wait for version 5.1.2

**Comment by diegobrum** [comment]
Try use

```
search.Filter(x => x.Names, query=> query.StartsWith("Jo"))
```

**Comment by diegobrum** [comment]
@pekic , please see v5.1.2
