### ISSUE TITLE
LoadSolrSchemaFields Fails with data_driven_schema

### ISSUE THREAD

**Issue by jokin** [solr-express/solr-express#241]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
AddSolrExpress fails when there are fields that are created automatically with the schemaless config. Solr schema doesn't return the indexed or stored property for these fields, for example could return something like:
```
  {
      "name":"name",
      "type":"strings"
}
```

at https://lucene.apache.org/solr/guide/6_6/schemaless-mode.html#SchemalessMode-ExamplesofIndexedDocuments there is a more complete example. 

and when registering the core at the startup, at the ExpresionBuilder.cs file, when parsing the json fails.

```
            this.FieldSchemas = allFields["fields"]
                .ToDictionary(
                    k => k["name"].Value<string>(),
                    v => new FieldSchema
                    {
                        FieldName = v["name"].Value<string>(),
                        IsIndexed = v["indexed"].Value<bool>(),
                        IsStored = v["stored"].Value<bool>()
                    });
````

A workarund it's to put a default value of false: 

```
            this.FieldSchemas = allFields["fields"]
                .ToDictionary(
                    k => k["name"].Value<string>(),
                    v => new FieldSchema
                    {
                        FieldName = v["name"].Value<string>(),
                        IsIndexed = v["indexed"]?.Value<bool>() ?? false,
                        IsStored = v["stored"]?.Value<bool>() ?? false
                    });
```
## Expected behavior

Don't fail when the schema doesn't have the indexed or stored property. 

## Minimal reproduction of the problem with instructions
Start a solr collection with the data_driven_schema, and add a document via the Gui with the field s that you want to have. 

## Environment

- Connect to a SOLR version: 6.4
- Connect to a SOLR in cloud mode? [X ] Yes [ ] No
- I'm coding using platform:  Windows 
- Using .net version:  net4.6,
- Using SolrExpress package: SolrExpress.Solr5
- Using SolrExpress package version: 5.1.1
- Using SolrExpress.DI package:  Autofac
- Using SolrExpress.DI package version: 5.1.1

**Comment by diegobrum** [comment]
@jokin , please see v5.1.2
