### ISSUE TITLE
Client certificates

### ISSUE THREAD

**Issue by ericnewton76** [solr-express/solr-express#243]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Cant specify client certificate for connection.  Probably need a way expose Http connection just before making call or something

## Expected behavior
Able to include an X509Certificate2 to the ClientCertificates of the request

**Comment by diegobrum** [comment]
https://github.com/solr-express/solr-express/commit/9c8f8a3984403bc0c5607723387d32add99586c6
