### ISSUE TITLE
Filter with Wildcard Searches

### ISSUE THREAD

**Issue by MarijaShakhrai** [solr-express/solr-express#245]
## I'm submitting an Extension Method for SolrExpress.Search.Parameter.Extension

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

Using Solr.Express I could not complete the request for Code:\*123\*, for example, just Code:"\*123\*", but it's not work for me 

## Expected behavior

I need smth like this or recommendation how I can make such a request using available tools
public SearchQuery<TDocument> Contains(string value)
		{
			return this.AddValue($"\*{value}\*", false);
		}

// using
documents
.Select()
.Filter(q => q.Code, q=>q.Contains("123"))
It already works for me locally

## Minimal reproduction of the problem with instructions
query - string with Solr query
I used to
documents
.Select()
.Query(query) 
but now it does not work like this

## Environment

- Connect to a SOLR version: 7.2.0
- Connect to a SOLR in cloud mode? [ ] Yes [x] No
- I'm coding using platform:  Windows
- Using .net version: netcoreapp2.0
- Using SolrExpress package: SolrExpress.Solr5
- Using SolrExpress package version: 5.1.2
- Using SolrExpress.DI package: Native .Net Core
- Using SolrExpress.DI package version: 5.1.2

**Comment by Baklap4** [comment]
With this i'd like to add a 'endswith' query aswell.. There's currently only support for 'query.startswith()'

**Comment by diegobrum** [comment]
Hi @MarijaShakhrai @Baklap4 

In version 5.4, use:

``` csharp
query.EndsWith(); // or
query.StartsWith(); // or
query.Contains();
```
