### ISSUE TITLE
Exception if solr is not available on startup application

### ISSUE THREAD

**Issue by Baklap4** [solr-express/solr-express#246]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Currently if the application starts and solr server is not up and ready to use, the application will crash since it couldn't connect to solr.

## Expected behavior
Startup of application continues (exception is catched), and server connection is made when server is live with X retries

## Minimal reproduction of the problem with instructions
Create a default dotnet project, add solr express library and point to solr server address.
Dont start solr.
Application crashes

## Environment

- Connect to a SOLR version: 6.5.0
- Connect to a SOLR in cloud mode? [ ] Yes [x] No
- I'm coding using platform:  Windows
- Using .net version: netcoreapp2.0
- Using SolrExpress package: SolrExpress.Solr5 using the dotnet DI.
- Using SolrExpress package version: 5.1.2
- Using SolrExpress.DI package: net core
- Using SolrExpress.DI package version: latest

**Comment by Baklap4** [comment]
Invalid.

**Comment by diegobrum** [comment]
Hi @Baklap4 , this issue make sense. See #259
