### ISSUE TITLE
Use min.count = 1 (Solr 5)

### ISSUE THREAD

**Issue by diegobrum** [solr-express/solr-express#50]
Use min.count = 1 in facet.range

**Comment by hheexx** [comment]
Can this be changed? mincount.

Can it be possible do to FacetField( x => x.y, mincount: 0) ?

**Comment by diegobrum** [comment]
Not in current version

But in v5, will be possible :)

**Comment by hheexx** [comment]
Cool! Any time estimate?

**Comment by diegobrum** [comment]
Maybe in next week

**Comment by hheexx** [comment]
Added?
Can't find it.

**Comment by hheexx** [comment]
@diegobrum

**Comment by diegobrum** [comment]
Hi @hheexx 
I'm working in version 5, wait for :)
