### ISSUE TITLE
.Execute does not return correct type or documentation incorrect

### ISSUE THREAD

**Issue by cstech-carlcamilleri** [solr-express/solr-express#508]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
</code></pre>

## Current behavior

Referring to https://solr-express.gitbook.io/docs/tutorials/getting-started :
<code>
var searchResult = techProducts
            .Select()
            .Fields(d => d.Id, d => d.Manufacturer)
            .FacetField(d => d.Categories)
            .Filter(d => d.Id, "205325092")
            .Execute();
</code>
Search result is of type  :
<code>
 IList<ISearchResult < TDocument>> 
</code>

This does not have  methods :
            **.Information(out var information)**
## Expected behavior

How do I get the list of documents from  IList<ISearchResult<TDocument>> ?

Thanks

**Comment by diegobrum** [comment]
Hi @cstech-carlcamilleri you need to use extension

``` csharp
using SolrExpress.Search.Parameter.Extension;
```
