### ISSUE TITLE
NullReferenceException in ValidateSearchItem() > CheckAnyParameter

### ISSUE THREAD

**Issue by Akaoni** [solr-express/solr-express#564]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

After upgrading to v5.4.0+ I get the following exception:

```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
   at SolrExpress.Search.DocumentSearch`1.ValidateSearchItem(ISearchItem item)
   at SolrExpress.Search.DocumentSearch`1.Add(ISearchItem item)
   at SolrExpress.Search.Extension.DocumentSearchExtension.Limit[TDocument](DocumentSearch`1 documentSearch, Int64 value)
   at SolrExpress53.Program.Main(String[] args) in <<PATH_TO_MY_PROJECT>>\SolrExpress5.3\Program.cs:line 24
```

## Expected behavior

Not getting an exception.

## Minimal reproduction of the problem with instructions

1. Create a new .NET Core v3.1 Console Application
1. Add the following NuGet packages
   * SolrExpress.Solr5 - v5.4.0+
   * SolrExpress.DI.CoreClr - v5.4.0+
1. Copy the following into Program.cs, replace "<<URL_TO_YOUR_SOLR_COLLECTION>>", and run:
```csharp
using Microsoft.Extensions.DependencyInjection;
using SolrExpress;
using SolrExpress.DI.CoreClr;
using SolrExpress.Search.Extension;
using SolrExpress.Search.Result;
using SolrExpress.Search.Result.Extension;
using SolrExpress.Solr5.Extension;
using System;

namespace SolrExpress54
{
    class Program
    {
        static void Main(string[] args)
        {
            ServiceProvider serviceProvider = new ServiceCollection()
                .AddSolrExpress<Document>(builder => builder
                    .UseHostAddress("<<URL_TO_YOUR_SOLR_COLLECTION>>")
                    .UseSolr5()
                )
                .BuildServiceProvider();

            serviceProvider.GetService<DocumentCollection<Document>>()
                .Select()
                .Limit(0)
                .Execute()
                .Information(out Information information);

            Console.WriteLine($"Document Count: {information.DocumentCount.ToString("N0")}");

            Console.WriteLine();
            Console.WriteLine("Press any key to exit...");
            Console.ReadKey();
        }
    }
}
```

## Environment

- Connect to a SOLR version: 5.4.1 and 8.2.0
- Connect to a SOLR in cloud mode? [X] Yes [ ] No
- I'm coding using platform:  Windows
- Using .net version: netcoreapp3.1
- Using SolrExpress package: SolrExpress.Solr5
- Using SolrExpress package version: 5.4.2
- Using SolrExpress.DI package: SolrExpress.DI.CoreClr
- Using SolrExpress.DI package version: 5.4.2

## Other
I had a look at what changed in the SolrExpress code and realised that setting _CheckAnyParameter_ = false gets rid of the exception. Perhaps the following line needs a null conditional in case _useAnyThanSpecificParameterRather_ is null?

```csharp
var isValid = ((IValidationAttribute)useAnyThanSpecificParameterRather).IsValid<TDocument>(searchParameter, out errorMessage);
```

**Comment by diegobrum** [comment]
Hi @Akaoni 

Thanks for your report

Please use version 5.5.0
